/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

/**
 *
 * @author pamel
 */

import Principal.Exe;
import java.awt.BorderLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import funciones.Ejecucion;
import java.awt.Color;
import java.awt.Desktop;
import java.io.File;
import DATA_analisis.Lexer;
import DATA_analisis.sintactico;
import Reportes.ReporteErrores;
import Reportes.ReporteTokens;

public class Ventana2 extends javax.swing.JFrame {

    /**
     * Creates new form Ventana2
     */
    public Ventana2() {
        
        initComponents();
        getContentPane().setBackground(Color.PINK);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAbrirArchivo = new javax.swing.JButton();
        btnAnalizarDatos = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        bntNuevoArchivo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Consola = new javax.swing.JTextArea();
        Panel = new javax.swing.JTabbedPane();
        jLabel2 = new javax.swing.JLabel();
        R_Token = new javax.swing.JButton();
        R_Error = new javax.swing.JButton();
        R_Tabla = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        btnAbrirArchivo.setBackground(new java.awt.Color(255, 51, 102));
        btnAbrirArchivo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAbrirArchivo.setForeground(new java.awt.Color(255, 255, 255));
        btnAbrirArchivo.setText("Abrir");
        btnAbrirArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbrirArchivoActionPerformed(evt);
            }
        });

        btnAnalizarDatos.setBackground(new java.awt.Color(255, 0, 102));
        btnAnalizarDatos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAnalizarDatos.setForeground(new java.awt.Color(255, 255, 255));
        btnAnalizarDatos.setText("Analizar");
        btnAnalizarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnalizarDatosActionPerformed(evt);
            }
        });

        btnGuardar.setBackground(new java.awt.Color(255, 0, 102));
        btnGuardar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        bntNuevoArchivo.setBackground(new java.awt.Color(255, 0, 102));
        bntNuevoArchivo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bntNuevoArchivo.setForeground(new java.awt.Color(255, 255, 255));
        bntNuevoArchivo.setText("Nuevo Archivo");
        bntNuevoArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntNuevoArchivoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Entradas");

        Consola.setBackground(new java.awt.Color(204, 153, 255));
        Consola.setColumns(20);
        Consola.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        Consola.setRows(5);
        Consola.setText("se mostrara el analisis aqui");
        jScrollPane1.setViewportView(Consola);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Consola");

        R_Token.setText("R. Token");
        R_Token.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R_TokenActionPerformed(evt);
            }
        });

        R_Error.setText("R. Errores");
        R_Error.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R_ErrorActionPerformed(evt);
            }
        });

        R_Tabla.setText("R. Tabla Simbolos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Panel, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAbrirArchivo)
                        .addGap(54, 54, 54)
                        .addComponent(btnAnalizarDatos)
                        .addGap(53, 53, 53)
                        .addComponent(btnGuardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bntNuevoArchivo)
                        .addGap(39, 39, 39)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(R_Error)
                .addGap(41, 41, 41)
                .addComponent(R_Token)
                .addGap(34, 34, 34)
                .addComponent(R_Tabla)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(597, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(376, 376, 376)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(R_Token)
                    .addComponent(R_Error)
                    .addComponent(R_Tabla))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Panel)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bntNuevoArchivo)
                            .addComponent(btnGuardar)
                            .addComponent(btnAnalizarDatos)
                            .addComponent(btnAbrirArchivo))
                        .addGap(16, 16, 16))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(16, Short.MAX_VALUE))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(425, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAbrirArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbrirArchivoActionPerformed
        // TODO add your handling code here:
        
        windowsFile.agregarPestanaDinamica(Panel);
    }//GEN-LAST:event_btnAbrirArchivoActionPerformed

    private void btnAnalizarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnalizarDatosActionPerformed
        // TODO add your handling code here:
        
        Consola.setText("");
        DatoAnalisis.analizarContenido(Panel, Consola);
        
        mostrarMensajeConsola(funciones.Ejecucion.cadenita);
        
       
    }//GEN-LAST:event_btnAnalizarDatosActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        
         windowsFile.guardarArchivo(Panel);
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void bntNuevoArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntNuevoArchivoActionPerformed
        // TODO add your handling code here:
        
         windowsFile.agregarNuevaPestana(Panel);
    }//GEN-LAST:event_bntNuevoArchivoActionPerformed

    private void R_ErrorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R_ErrorActionPerformed
        // TODO add your handling code here:
        try{
            ReporteErrores.generarReporteERR(DATA_analisis.Lexer.errorsitos);
            
            File archivito = new File("erroresLexicos.html");
            if(!Desktop.isDesktopSupported()){
                System.out.println("no sopórtado");
                return ;
            }
            Desktop escritorio = Desktop.getDesktop();
            if(archivito.exists()){
                System.out.println("Se encontro");
                escritorio.open(archivito);
            }
            
            }catch(Exception a){
                
                System.out.println("Error al abrir el archivo");
            }
    }//GEN-LAST:event_R_ErrorActionPerformed

    private void R_TokenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R_TokenActionPerformed
        // TODO add your handling code here:
         try{
            ReporteTokens.generarReporteTOK(DATA_analisis.Lexer.tokensito);
           
            
            File archivito = new File("reporteTOKEN.html");
            if(!Desktop.isDesktopSupported()){
                System.out.println("no sopórtado");
                return ;
            }
            Desktop escritorio = Desktop.getDesktop();
            if(archivito.exists()){
                System.out.println("Se encontro");
                escritorio.open(archivito);
            }
            
            }catch(Exception a){
                
                System.out.println("Error al abrir el archivo");
            }
        
    }//GEN-LAST:event_R_TokenActionPerformed

    public  void mostrarMensajeConsola(String mensaje) {
        Consola.append(mensaje + "\n");
    }
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana2().setVisible(true);
            }
        });
        
    }
    
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextArea Consola;
    private javax.swing.JTabbedPane Panel;
    private javax.swing.JButton R_Error;
    private javax.swing.JButton R_Tabla;
    private javax.swing.JButton R_Token;
    private javax.swing.JButton bntNuevoArchivo;
    private javax.swing.JButton btnAbrirArchivo;
    private javax.swing.JButton btnAnalizarDatos;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
