// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: lexico.jflex


package DATA_analisis; 
import java_cup.runtime.*;
import java.util.LinkedList;
import Reportes.ErroresLex;
import Reportes.Token; 

/*------------------ 2da Area: Opciones y Declaraciones ------------------*/

@SuppressWarnings("fallthrough")
public class Lexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\1\u0100\36\u0200\1\u0300\267\u0200\10\u0400\u1020\u0200";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\1\3\2\1\22\0\1\4\1\5"+
    "\1\6\5\0\1\7\1\10\1\0\1\11\1\12\1\13"+
    "\1\14\1\0\12\15\1\16\1\17\1\20\1\21\1\22"+
    "\1\0\1\23\1\24\1\25\1\26\1\27\1\30\1\31"+
    "\1\32\1\33\1\34\2\31\1\35\1\36\1\37\1\40"+
    "\1\41\1\31\1\42\1\43\1\44\1\45\1\46\1\31"+
    "\1\47\1\31\1\50\1\51\1\0\1\52\1\0\1\53"+
    "\1\0\1\24\1\25\1\26\1\27\1\30\1\31\1\32"+
    "\1\33\1\34\2\31\1\35\1\36\1\37\1\40\1\41"+
    "\1\31\1\42\1\43\1\44\1\45\1\46\1\31\1\47"+
    "\1\31\1\50\12\0\1\3\252\0\2\54\115\0\1\55"+
    "\u01a8\0\2\3\326\0\u0100\3";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1280];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\1\1\4\1\5\1\6"+
    "\1\7\1\10\1\11\1\12\1\13\1\14\1\15\1\16"+
    "\1\1\12\17\1\20\1\21\1\1\1\3\1\0\1\22"+
    "\2\0\1\23\5\17\1\0\6\17\1\0\4\17\1\0"+
    "\1\24\1\0\1\25\3\17\1\26\1\17\1\26\1\27"+
    "\1\30\1\17\1\31\1\32\1\33\1\31\2\17\1\0"+
    "\2\34\1\35\1\36\1\35\1\37\1\40\2\17\1\0"+
    "\1\17\1\0\1\17\1\0\1\41\2\17\1\0\1\17"+
    "\1\0\2\17\1\0\1\17\1\0\2\42\1\43\1\17"+
    "\1\43\1\17\1\0\1\44\1\17\1\0\1\45\1\0"+
    "\1\17\1\0\2\17\1\0\2\46\1\0\2\47\1\50"+
    "\1\17\2\0\2\51\2\0\1\52";

  private static int [] zzUnpackAction() {
    int [] result = new int[129];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\56\0\56\0\134\0\212\0\56\0\56\0\56"+
    "\0\56\0\56\0\270\0\56\0\56\0\346\0\56\0\56"+
    "\0\u0114\0\u0142\0\u0170\0\u019e\0\u01cc\0\u01fa\0\u0228\0\u0256"+
    "\0\u0284\0\u02b2\0\u02e0\0\56\0\56\0\u030e\0\56\0\212"+
    "\0\56\0\u033c\0\u036a\0\u0398\0\u03c6\0\u03f4\0\u0422\0\u0450"+
    "\0\u047e\0\u04ac\0\u04da\0\u0508\0\u0536\0\u0564\0\u0592\0\u05c0"+
    "\0\u05ee\0\u061c\0\u064a\0\u0678\0\u06a6\0\u06d4\0\u033c\0\u0702"+
    "\0\u0170\0\u0730\0\u075e\0\u078c\0\u0170\0\u07ba\0\56\0\u07e8"+
    "\0\u0170\0\u0816\0\u0170\0\u0844\0\u0170\0\56\0\u0872\0\u08a0"+
    "\0\u08ce\0\u0170\0\56\0\u0170\0\u08fc\0\56\0\56\0\u0170"+
    "\0\u092a\0\u0958\0\u0986\0\u09b4\0\u09e2\0\u0a10\0\u0a3e\0\u0170"+
    "\0\u0a6c\0\u0a9a\0\u0ac8\0\u0af6\0\u0b24\0\u0b52\0\u0b80\0\u0bae"+
    "\0\u0bdc\0\u0c0a\0\u0c38\0\u0c66\0\u0170\0\u0c94\0\56\0\u0cc2"+
    "\0\u0cf0\0\u0170\0\u0d1e\0\u0d4c\0\u0170\0\u0d7a\0\u0da8\0\u0dd6"+
    "\0\u0e04\0\u0e32\0\u0e60\0\u0170\0\56\0\u0e8e\0\u0170\0\56"+
    "\0\u0170\0\u0ebc\0\u0eea\0\u0f18\0\u0170\0\56\0\u0f46\0\u0f74"+
    "\0\56";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[129];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\2\3\1\0\1\3\1\4\1\5\1\6\1\7"+
    "\1\10\1\11\1\12\1\2\1\13\1\14\1\15\1\16"+
    "\1\17\1\20\1\21\1\22\1\23\1\24\1\25\1\26"+
    "\5\23\1\27\2\23\1\30\1\31\1\32\2\23\1\33"+
    "\2\23\1\34\1\35\2\2\1\36\56\0\2\4\1\37"+
    "\53\4\2\40\1\0\3\40\1\41\47\40\14\0\1\42"+
    "\1\13\45\0\1\43\74\0\25\44\22\0\1\23\6\0"+
    "\16\23\1\45\6\23\2\0\1\23\17\0\1\23\6\0"+
    "\25\23\2\0\1\23\17\0\1\23\6\0\7\23\1\46"+
    "\4\23\1\47\10\23\2\0\1\23\17\0\1\23\6\0"+
    "\10\23\1\50\3\23\1\51\10\23\2\0\1\23\1\52"+
    "\16\0\1\23\6\0\13\23\1\53\11\23\2\0\1\23"+
    "\17\0\1\23\6\0\1\54\3\23\1\55\3\23\1\56"+
    "\3\23\1\57\4\23\1\60\3\23\2\0\1\23\1\61"+
    "\16\0\1\23\6\0\16\23\1\62\6\23\2\0\1\23"+
    "\17\0\1\23\6\0\4\23\1\63\20\23\2\0\1\23"+
    "\17\0\1\23\6\0\21\23\1\64\3\23\2\0\1\23"+
    "\17\0\1\23\6\0\1\65\24\23\2\0\1\23\47\0"+
    "\1\66\25\0\1\67\40\0\5\43\1\70\50\43\15\0"+
    "\1\44\6\0\25\44\2\0\1\44\17\0\1\23\6\0"+
    "\16\23\1\71\6\23\2\0\1\23\17\0\1\23\6\0"+
    "\1\72\24\23\2\0\1\23\17\0\1\23\6\0\11\23"+
    "\1\73\1\23\1\74\11\23\2\0\1\23\17\0\1\23"+
    "\6\0\22\23\1\75\2\23\2\0\1\23\17\0\1\23"+
    "\6\0\21\23\1\76\3\23\2\0\1\23\50\0\1\77"+
    "\24\0\1\23\6\0\3\23\1\100\21\23\2\0\1\23"+
    "\17\0\1\23\6\0\23\23\1\101\1\23\2\0\1\23"+
    "\17\0\1\23\6\0\3\23\1\102\21\23\2\0\1\23"+
    "\17\0\1\23\6\0\13\23\1\103\11\23\2\0\1\23"+
    "\17\0\1\23\6\0\3\23\1\104\21\23\2\0\1\23"+
    "\17\0\1\23\6\0\11\23\1\105\13\23\2\0\1\23"+
    "\41\0\1\106\33\0\1\23\6\0\10\23\1\107\3\23"+
    "\1\110\10\23\2\0\1\23\1\111\16\0\1\23\6\0"+
    "\17\23\1\112\5\23\2\0\1\23\1\0\1\113\15\0"+
    "\1\23\6\0\12\23\1\114\12\23\2\0\1\23\17\0"+
    "\1\23\6\0\16\23\1\115\6\23\2\0\1\23\40\0"+
    "\1\116\41\0\1\117\50\0\1\23\6\0\16\23\1\120"+
    "\6\23\2\0\1\23\17\0\1\23\6\0\21\23\1\121"+
    "\3\23\2\0\1\23\17\0\1\23\6\0\17\23\1\122"+
    "\5\23\2\0\1\23\1\0\1\123\15\0\1\23\6\0"+
    "\1\23\1\124\23\23\2\0\1\23\6\0\1\125\10\0"+
    "\1\23\6\0\25\23\2\0\1\23\17\0\1\23\6\0"+
    "\10\23\1\126\14\23\2\0\1\23\1\127\16\0\1\23"+
    "\6\0\1\130\24\23\2\0\1\23\17\0\1\23\6\0"+
    "\13\23\1\131\11\23\2\0\1\23\17\0\1\23\6\0"+
    "\6\23\1\132\16\23\2\0\1\23\41\0\1\133\33\0"+
    "\1\23\6\0\10\23\1\134\14\23\2\0\1\23\1\135"+
    "\16\0\1\23\6\0\12\23\1\136\12\23\2\0\1\23"+
    "\17\0\1\23\6\0\14\23\1\137\10\23\2\0\1\23"+
    "\42\0\1\140\32\0\1\23\6\0\11\23\1\141\13\23"+
    "\2\0\1\23\43\0\1\142\31\0\1\23\6\0\1\143"+
    "\24\23\2\0\1\23\26\0\1\144\46\0\1\23\6\0"+
    "\20\23\1\145\4\23\2\0\1\23\17\0\1\23\6\0"+
    "\16\23\1\146\6\23\2\0\1\23\46\0\1\147\26\0"+
    "\1\23\6\0\1\150\24\23\2\0\1\23\26\0\1\151"+
    "\46\0\1\23\6\0\13\23\1\152\11\23\2\0\1\23"+
    "\17\0\1\23\6\0\11\23\1\153\13\23\2\0\1\23"+
    "\37\0\1\154\35\0\1\23\6\0\4\23\1\155\20\23"+
    "\2\0\1\23\44\0\1\156\30\0\1\23\6\0\13\23"+
    "\1\157\11\23\2\0\1\23\41\0\1\160\33\0\1\23"+
    "\6\0\1\161\24\23\2\0\1\23\17\0\1\23\6\0"+
    "\13\23\1\162\11\23\2\0\1\23\41\0\1\163\33\0"+
    "\1\23\6\0\4\23\1\164\20\23\2\0\1\23\32\0"+
    "\1\165\65\0\1\166\32\0\1\23\6\0\1\167\24\23"+
    "\2\0\1\23\26\0\1\170\46\0\1\23\6\0\12\23"+
    "\1\171\12\23\2\0\1\23\17\0\1\23\6\0\24\23"+
    "\1\172\2\0\1\23\52\0\1\173\37\0\1\174\40\0"+
    "\1\23\6\0\1\175\24\23\2\0\1\23\26\0\1\176"+
    "\73\0\1\177\37\0\1\200\67\0\1\201\17\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[4002];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\2\11\2\1\5\11\1\1\2\11\1\1\2\11"+
    "\13\1\2\11\1\1\1\11\1\0\1\11\2\0\6\1"+
    "\1\0\6\1\1\0\4\1\1\0\1\1\1\0\6\1"+
    "\1\11\6\1\1\11\2\1\1\0\1\1\1\11\2\1"+
    "\2\11\3\1\1\0\1\1\1\0\1\1\1\0\3\1"+
    "\1\0\1\1\1\0\2\1\1\0\1\1\1\0\4\1"+
    "\1\11\1\1\1\0\2\1\1\0\1\1\1\0\1\1"+
    "\1\0\2\1\1\0\1\1\1\11\1\0\1\1\1\11"+
    "\2\1\2\0\1\1\1\11\2\0\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[129];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */
    //---> Codigo de usuario en sintaxis java
   public static LinkedList<ErroresLex> errorsitos = new LinkedList<ErroresLex>();
   public static LinkedList<Token> tokensito = new LinkedList<Token>();
    


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
    System.out.println("analisis completo");
    //System.out.println(TablaEL.toString());
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { errorsitos.add(new ErroresLex("Error lexico" , yytext() + "",  (yyline) + 1, (yycolumn) + 1));
                    
                    //System.out.println("Error Lexico: " + yytext() + " | Fila:" + yyline + " | Columna: " + yycolumn);
            }
          // fall through
          case 43: break;
          case 2:
            { /* Espacios en blanco se ignoran */
            }
          // fall through
          case 44: break;
          case 3:
            { /* Ignorar comentario de una línea */
            }
          // fall through
          case 45: break;
          case 4:
            { tokensito.add(new Token(yytext(),"Simbolo",(yyline) + 1, (yycolumn) + 1)); return new Symbol(sym.PAR_IZQUIERDO, yycolumn, yyline, yytext());
            }
          // fall through
          case 46: break;
          case 5:
            { tokensito.add(new Token(yytext(),"Simbolo",(yyline) + 1, (yycolumn) + 1)); return new Symbol(sym.PAR_DERECHO, yycolumn, yyline, yytext());
            }
          // fall through
          case 47: break;
          case 6:
            { tokensito.add(new Token(yytext(),"Operador",(yyline) + 1, (yycolumn) + 1));
            return new Symbol(sym.MAS, yycolumn, yyline, yytext());
            }
          // fall through
          case 48: break;
          case 7:
            { tokensito.add(new Token(yytext(),"Simbolo",(yyline) + 1, (yycolumn) + 1)); return new Symbol(sym.COMA, yycolumn, yyline, yytext());
            }
          // fall through
          case 49: break;
          case 8:
            { tokensito.add(new Token(yytext(),"Simbolo",(yyline) + 1, (yycolumn) + 1)); return new Symbol(sym.GUION, yycolumn, yyline, yytext());
            }
          // fall through
          case 50: break;
          case 9:
            { tokensito.add(new Token(yytext(),"Expresion",(yyline) + 1, (yycolumn) + 1));
            return new Symbol(sym.ENTERO, yycolumn, yyline, yytext());
            }
          // fall through
          case 51: break;
          case 10:
            { tokensito.add(new Token(yytext(),"Simbolo",(yyline) + 1, (yycolumn) + 1)); return new Symbol(sym.DOSP, yycolumn, yyline, yytext());
            }
          // fall through
          case 52: break;
          case 11:
            { tokensito.add(new Token(yytext(),"Simbolo",(yyline) + 1, (yycolumn) + 1)); return new Symbol(sym.PYC, yycolumn, yyline, yytext());
            }
          // fall through
          case 53: break;
          case 12:
            { tokensito.add(new Token(yytext(),"Simbolo",(yyline) + 1, (yycolumn) + 1)); return new Symbol(sym.MENORQ, yycolumn, yyline, yytext());
            }
          // fall through
          case 54: break;
          case 13:
            { tokensito.add(new Token(yytext(),"Simbolo",(yyline) + 1, (yycolumn) + 1)); return new Symbol(sym.IGUAL, yycolumn, yyline, yytext());
            }
          // fall through
          case 55: break;
          case 14:
            { tokensito.add(new Token(yytext(),"Simbolo",(yyline) + 1, (yycolumn) + 1)); return new Symbol(sym.MAYORQ, yycolumn, yyline, yytext());
            }
          // fall through
          case 56: break;
          case 15:
            { tokensito.add(new Token(yytext(),"Expresion",(yyline) + 1, (yycolumn) + 1));
            return new Symbol(sym.ID, yycolumn, yyline, yytext());
            }
          // fall through
          case 57: break;
          case 16:
            { tokensito.add(new Token(yytext(),"Simbolo",(yyline) + 1, (yycolumn) + 1));
            return new Symbol(sym.CORIZQ, yycolumn, yyline, yytext());
            }
          // fall through
          case 58: break;
          case 17:
            { tokensito.add(new Token(yytext(),"Simbolo",(yyline) + 1, (yycolumn) + 1));
            return new Symbol(sym.CORDER, yycolumn, yyline, yytext());
            }
          // fall through
          case 59: break;
          case 18:
            { tokensito.add(new Token(yytext(),"Expresion",(yyline) + 1, (yycolumn) + 1));
            return new Symbol(sym.CADENA, yycolumn, yyline, yytext());
            }
          // fall through
          case 60: break;
          case 19:
            { tokensito.add(new Token(yytext(),"Expresion",(yyline) + 1, (yycolumn) + 1));
            return new Symbol(sym.IDARROBA, yycolumn, yyline, yytext());
            }
          // fall through
          case 61: break;
          case 20:
            { tokensito.add(new Token(yytext(),"Expresion",(yyline) + 1, (yycolumn) + 1));
            return new Symbol(sym.DECIMAL, yycolumn, yyline, yytext());
            }
          // fall through
          case 62: break;
          case 21:
            { tokensito.add(new Token(yytext(),"Reservada",(yyline) + 1, (yycolumn) + 1)); return new Symbol(sym.ARROBA, yycolumn, yyline, yytext());
            }
          // fall through
          case 63: break;
          case 22:
            { tokensito.add(new Token(yytext(),"Reservada",(yyline) + 1, (yycolumn) + 1)); return new Symbol(sym.DIVISION, yycolumn, yyline, yytext());
            }
          // fall through
          case 64: break;
          case 23:
            { tokensito.add(new Token(yytext(),"Reservada",(yyline) + 1, (yycolumn) + 1)); return new Symbol(sym.END, yycolumn, yyline, yytext());
            }
          // fall through
          case 65: break;
          case 24:
            { tokensito.add(new Token(yytext(),"Reservada",(yyline) + 1, (yycolumn) + 1)); return new Symbol(sym.MAX, yycolumn, yyline, yytext());
            }
          // fall through
          case 66: break;
          case 25:
            { tokensito.add(new Token(yytext(),"Reservada",(yyline) + 1, (yycolumn) + 1)); return new Symbol(sym.MIN, yycolumn, yyline, yytext());
            }
          // fall through
          case 67: break;
          case 26:
            { tokensito.add(new Token(yytext(),"Reservada",(yyline) + 1, (yycolumn) + 1)); return new Symbol(sym.MOD, yycolumn, yyline, yytext());
            }
          // fall through
          case 68: break;
          case 27:
            { tokensito.add(new Token(yytext(),"Reservada",(yyline) + 1, (yycolumn) + 1)); return new Symbol(sym.MULTIPLICACION, yycolumn, yyline, yytext());
            }
          // fall through
          case 69: break;
          case 28:
            { tokensito.add(new Token(yytext(),"Reservada",(yyline) + 1, (yycolumn) + 1)); return new Symbol(sym.RESTA, yycolumn, yyline, yytext());
            }
          // fall through
          case 70: break;
          case 29:
            { tokensito.add(new Token(yytext(),"Reservada",(yyline) + 1, (yycolumn) + 1)); return new Symbol(sym.SUMA, yycolumn, yyline, yytext());
            }
          // fall through
          case 71: break;
          case 30:
            { tokensito.add(new Token(yytext(),"Reservada",(yyline) + 1, (yycolumn) + 1)); return new Symbol(sym.VARIABLE, yycolumn, yyline, yytext());
            }
          // fall through
          case 72: break;
          case 31:
            { /* Ignorar comentario multilinea */
            }
          // fall through
          case 73: break;
          case 32:
            { tokensito.add(new Token(yytext(),"Reservada",(yyline) + 1, (yycolumn) + 1)); return new Symbol(sym.CHARVAR, yycolumn, yyline, yytext());
            }
          // fall through
          case 74: break;
          case 33:
            { tokensito.add(new Token(yytext(),"Reservada",(yyline) + 1, (yycolumn) + 1)); return new Symbol(sym.MODA, yycolumn, yyline, yytext());
            }
          // fall through
          case 75: break;
          case 34:
            { tokensito.add(new Token(yytext(),"Reservada",(yyline) + 1, (yycolumn) + 1)); return new Symbol(sym.MEDIA, yycolumn, yyline, yytext());
            }
          // fall through
          case 76: break;
          case 35:
            { tokensito.add(new Token(yytext(),"Reservada",(yyline) + 1, (yycolumn) + 1)); return new Symbol(sym.PRINT, yycolumn, yyline, yytext());
            }
          // fall through
          case 77: break;
          case 36:
            { tokensito.add(new Token(yytext(),"Reservada",(yyline) + 1, (yycolumn) + 1)); return new Symbol(sym.COLUMN, yycolumn, yyline, yytext());
            }
          // fall through
          case 78: break;
          case 37:
            { tokensito.add(new Token(yytext(),"Reservada",(yyline) + 1, (yycolumn) + 1)); return new Symbol(sym.DOUBLEVARIABLE, yycolumn, yyline, yytext());
            }
          // fall through
          case 79: break;
          case 38:
            { tokensito.add(new Token(yytext(),"Reservada",(yyline) + 1, (yycolumn) + 1)); return new Symbol(sym.CONSOLE, yycolumn, yyline, yytext());
            }
          // fall through
          case 80: break;
          case 39:
            { tokensito.add(new Token(yytext(),"Reservada",(yyline) + 1, (yycolumn) + 1)); return new Symbol(sym.MEDIANA, yycolumn, yyline, yytext());
            }
          // fall through
          case 81: break;
          case 40:
            { tokensito.add(new Token(yytext(),"Reservada",(yyline) + 1, (yycolumn) + 1)); return new Symbol(sym.PROGRAM, yycolumn, yyline, yytext());
            }
          // fall through
          case 82: break;
          case 41:
            { tokensito.add(new Token(yytext(),"Reservada",(yyline) + 1, (yycolumn) + 1)); return new Symbol(sym.VARIANZA, yycolumn, yyline, yytext());
            }
          // fall through
          case 83: break;
          case 42:
            { return new Symbol(sym.ENDPROGRAM, yycolumn, yyline, yytext());
            }
          // fall through
          case 84: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
