
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package DATA_analisis;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int NUMERO = 5;
  public static final int DOSPUNTOS = 13;
  public static final int PUNTO_Y_COMA = 4;
  public static final int COR_IZQUIERDO = 21;
  public static final int RESTA = 26;
  public static final int MAYORQUE = 19;
  public static final int IGUAL = 10;
  public static final int COLUMN = 38;
  public static final int ARROBA = 24;
  public static final int PAR_DERECHO = 2;
  public static final int ENDPROGRAM = 18;
  public static final int GUION = 16;
  public static final int SUMA = 25;
  public static final int MIN = 35;
  public static final int ID = 7;
  public static final int MEDIANA = 31;
  public static final int EOF = 0;
  public static final int VARIABLECHAR = 20;
  public static final int error = 1;
  public static final int PROGRAM = 17;
  public static final int DIGITO = 8;
  public static final int COMA = 9;
  public static final int MODA = 32;
  public static final int MOD = 29;
  public static final int COR_DERECHO = 22;
  public static final int PAR_IZQUIERDO = 3;
  public static final int MENORQUE = 14;
  public static final int STRCADENA = 6;
  public static final int VARIANZA = 33;
  public static final int END = 15;
  public static final int ARR = 23;
  public static final int MEDIA = 30;
  public static final int DOUBLEVAR = 12;
  public static final int DIVISION = 28;
  public static final int MAX = 34;
  public static final int VAR = 11;
  public static final int CONSOLE = 37;
  public static final int PRINT = 36;
  public static final int MULTIPLICACION = 27;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PAR_DERECHO",
  "PAR_IZQUIERDO",
  "PUNTO_Y_COMA",
  "NUMERO",
  "STRCADENA",
  "ID",
  "DIGITO",
  "COMA",
  "IGUAL",
  "VAR",
  "DOUBLEVAR",
  "DOSPUNTOS",
  "MENORQUE",
  "END",
  "GUION",
  "PROGRAM",
  "ENDPROGRAM",
  "MAYORQUE",
  "VARIABLECHAR",
  "COR_IZQUIERDO",
  "COR_DERECHO",
  "ARR",
  "ARROBA",
  "SUMA",
  "RESTA",
  "MULTIPLICACION",
  "DIVISION",
  "MOD",
  "MEDIA",
  "MEDIANA",
  "MODA",
  "VARIANZA",
  "MAX",
  "MIN",
  "PRINT",
  "CONSOLE",
  "COLUMN"
  };
}

