
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package DATA_analisis;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MENORQ = 15;
  public static final int ENTERO = 6;
  public static final int CHARVAR = 22;
  public static final int RESTA = 28;
  public static final int IDARROBA = 26;
  public static final int IGUAL = 11;
  public static final int COLUMN = 40;
  public static final int CORDER = 24;
  public static final int ARROBA = 25;
  public static final int PAR_DERECHO = 3;
  public static final int ENDPROGRAM = 19;
  public static final int GUION = 17;
  public static final int SUMA = 27;
  public static final int MIN = 37;
  public static final int ID = 8;
  public static final int EXCL = 2;
  public static final int MEDIANA = 33;
  public static final int EOF = 0;
  public static final int DECIMAL = 9;
  public static final int DOUBLEVARIABLE = 13;
  public static final int error = 1;
  public static final int PROGRAM = 18;
  public static final int COMA = 10;
  public static final int CADENA = 7;
  public static final int MODA = 34;
  public static final int MOD = 31;
  public static final int PAR_IZQUIERDO = 4;
  public static final int MAYORQ = 20;
  public static final int VARIABLE = 12;
  public static final int VARIANZA = 35;
  public static final int DOSP = 14;
  public static final int END = 16;
  public static final int MEDIA = 32;
  public static final int CORIZQ = 23;
  public static final int DIVISION = 30;
  public static final int MAX = 36;
  public static final int CONSOLE = 39;
  public static final int PRINT = 38;
  public static final int PYC = 5;
  public static final int MULTIPLICACION = 29;
  public static final int MAS = 21;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "EXCL",
  "PAR_DERECHO",
  "PAR_IZQUIERDO",
  "PYC",
  "ENTERO",
  "CADENA",
  "ID",
  "DECIMAL",
  "COMA",
  "IGUAL",
  "VARIABLE",
  "DOUBLEVARIABLE",
  "DOSP",
  "MENORQ",
  "END",
  "GUION",
  "PROGRAM",
  "ENDPROGRAM",
  "MAYORQ",
  "MAS",
  "CHARVAR",
  "CORIZQ",
  "CORDER",
  "ARROBA",
  "IDARROBA",
  "SUMA",
  "RESTA",
  "MULTIPLICACION",
  "DIVISION",
  "MOD",
  "MEDIA",
  "MEDIANA",
  "MODA",
  "VARIANZA",
  "MAX",
  "MIN",
  "PRINT",
  "CONSOLE",
  "COLUMN"
  };
}

